#!/bin/bash

p_check(){
if ! pgrep -a tor >/dev/null 2>&1 || ! ss -tulpn | grep -IE "tor" >/dev/null 2>&1; then
      archnon restart >/dev/null 2>&1     
else
      pkill -9 archdaemon && archdaemon &
fi
}

while true; do
   p_check >/dev/null 2>&1
done & >/dev/null 2>&1


