#!/bin/bash

# Colors

RED="\e[1;31m"

GREEN="\e[1;32m"

BLUE="\e[1;34m"

P="\e[1;35m"

YELLOW="\e[1;33m"

ORANGE="\e[38;5;214m"

LB="\e[36m"

NC="\e[0m"

### Banner ###
echo -e "\n${GREEN}<[${LB} MacTool ${YELLOW}v1.0.0 ${NC}By: ${ORANGE}newmasterone27@gmail.com ${GREEN}]>${NC}"

usage(){
echo -e "\n${ORANGE}[${YELLOW}!${ORANGE}]${LB} usage: ${P}sudo mactool ${NC}<${LB}option${NC}>${NC}"
echo -e "\n${BLUE}[${ORANGE}1${BLUE}]${ORANGE} change${BLUE}|${ORANGE}--device${BLUE}|${ORANGE}-d${NC}: ${GREEN}Change MAC Addr of a single device${NC}"
echo -e "\n${BLUE}[${ORANGE}2${BLUE}]${ORANGE} --enable${BLUE}|${ORANGE}enable${NC}: ${GREEN}Enable ${LB}MAC changing on boot, ${P}usage: ${BLUE}sudo mactool enable ${NC}<${LB}device${NC}>"
echo -e "\n${BLUE}[${ORANGE}3${BLUE}]${ORANGE} --disable${BLUE}|${ORANGE}disable${NC}: ${RED}Disable ${LB}MAC changeing on boot${NC}"
echo -e "\n${BLUE}[${ORANGE}4${BLUE}]${ORANGE} --daemon${BLUE}|${ORANGE}daemon${NC}: ${BLUE}Daemonize MAC changing by giving an interval, ${BLUE}usage: ${P}sudo mactool ${BLUE}--daemon ${NC}<${LB}device${NC}> ${NC}<${LB}secs${NC}>${NC}"
echo -e "\n${BLUE}[${ORANGE}5${BLUE}]${ORANGE} restore${BLUE}|${ORANGE}--reset${BLUE}|${ORANGE}reset${NC}: ${YELLOW}Reset Device's MAC Addr to permanent default${NC}"
echo -e "\n${BLUE}[${ORANGE}6${BLUE}]${ORANGE} --show-devices${BLUE}|${ORANGE}show${NC}: ${LB}Show Available Devices${NC}"
echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${RED} Use in case of emergency, it kills your internet connection !!${NC}"
}

if ! command -v macchanger >/dev/null 2>&1; then
	if [[ $(command -v apt) ]]; then
		if ! apt install -y macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v pacman) ]]; then
		if ! pacman -Sy --noconfirm --needed --overwrite "*" macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v dnf) ]]; then
		if ! dnf install -y --allowerasing macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v yum) ]]; then
		if ! yum install -y macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v xbps-install) ]]; then
		if ! xbps-install -Sy -f -y "*" macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v zypper) ]]; then
		if ! zypper install macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v apk) ]]; then
		if ! apk add --no-cache macchanger; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	elif [[ $(command -v emerge) ]]; then
		if ! emerge -v --oneshot --keep-going; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not install missing binary: ${ORANGE}macchanger${NC}"
		exit 1
		fi
	else
		echo -e "\n${RED}[${NC}-${RED}]${NC} Not common: ${RED}Unsuported pkg manager, please install: ${ORANGE}'macchanger'${NC}"
		exit 1
	fi
fi

change(){
ip link set $device down >/dev/null 2>&1

macchanger -r -b $device >/dev/null 2>&1

ip link set $device up >/dev/null 2>&1
}

restore(){
ip link set $device down >/dev/null 2>&1

macchanger -p $device >/dev/null 2>&1

ip link set $device up >/dev/null 2>&1
}

createsv(){
if [ ! -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then
    touch /etc/systemd/system/mactool.service

echo -e "\n[Unit]\nDescription=MacTool Service\n[Service]\nType=forking\nExecStart=mactool -d $device\nRemainAfterExit=yes\nUser=root\n[Install]\nWantedBy=multi-user.target" >> /etc/systemd/system/mactool.service

fi

if [ ! -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then
    mkdir -p /etc/sv/mactool/
    touch /etc/sv/mactool/run
 
    echo -e "#!/bin/sh\nexec mactool -d $device" >> /etc/sv/mactool/run
    chmod +x /etc/sv/mactool/run
fi

if [ ! -f /etc/init.d/mactool ] && command -v rc-service >/dev/null 2>&1; then
    touch /etc/init.d/mactool

echo "#!/sbin/openrc-run\nname=MacTool service\ncommand="mactool"\ncommand_args="-d $device"\ncommand_background=true\npidfile="/run/${RC_SVCNAME}.pid"\ndepend() {\n   need net\n}" >> /etc/init.d/mactool

   chmod +x /etc/init.d/mactool >/dev/null 2>&1
fi
}

enable(){

if [ -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then

    if systemctl is-enabled mactool >/dev/null 2>&1; then
       echo -e "\n${P}[${NC}*${P}]${NC} MacTool is enabled${NC}"
    else
        systemctl enable mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enabled${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
    fi
fi

if [ -f /etc/sv/mactool/run ] && command -v runit >/dev/null 2>&1; then

	if [ -d /run/runit/service ]; then
	    RSDIR=/run/runit/service
	elif [ -d /etc/service ]; then
	      RSDIR=/etc/service
	elif [ -d /var/run/service ]; then
	      RSDIR=/var/run/service
	fi

      if ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
            echo -e "\n${P}[${NC}*${P}]${NC} MacTool is enabled${NC}"
      else
           ln -s /etc/sv/mactool $RSDIR >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enabled${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
      fi
fi

if [ -f /etc/init.d/mactool ] && command -v rc-update >/dev/null 2>&1; then

      if sudo rc-update | grep -iE "mactool" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${GREEN} MacTool is enabled${NC}"
      else
           sudo rc-update add mactool default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}+${ORANGE}]${NC} Now MacTool is enable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not enable MacTool${NC}"
      fi
fi
}

disable(){
if [ -f /etc/systemd/system/mactool.service ] && command -v systemctl >/dev/null 2>&1; then

    if ! systemctl is-enabled mactool >/dev/null 2>&1; then
        echo -e "\n${RED}[${NC}+${RED}]${NC} MacTool is disabled${NC}"
        exit 0
    else

    systemctl disable mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
    exit 1
    fi
fi

if [ -f /etc/sv/mactool/run ] && command -v runit  >/dev/null 2>&1; then

      if [ -d /run/runit/service ]; then
	  RSDIR=/run/runit/service

      elif [ -d /etc/service ]; then
	      RSDIR=/etc/service
	
      elif [ -d /var/run/service ]; then
	      RSDIR=/var/run/service
      fi

      if ! ls -l $RSDIR/mactool/ >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} MacTool is already disabled${NC}"
           exit 0
      else

      rm -rf $RSDIR/mactool >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
      exit 1
      fi
fi

if [ -f /etc/init.d/mactool ] && command -v rc-service  >/dev/null 2>&1; then

      if ! rc-update | grep -iE "mactool" >/dev/null 2>&1; then
           echo -e "\n${P}[${NC}*${P}]${NC} MacTool is already disabled${NC}"
           exit 0
      else

      rc-update del mactool default >/dev/null 2>&1 && echo -e "\n${ORANGE}[${NC}*${ORANGE}]${NC} MacTool has been disable${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not disable MacTool${NC}"
      exit 1
      fi
fi
}

dlist(){
echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Daemon List By PID${LB}(${GREEN}active${BLUE})${NC}: ${ORANGE}"
pgrep -a mactd && echo -e "${NC}"
echo -e "\n${RED}[${NC}-${RED}]${NC} Kill them by running: ${RED}sudo pkill -9 mactd${NC}"
}

while [ $# -gt 0 ]; do
	case $1 in
	
	change|--device|-d)
	mode=1
	device=$2
	
	if [ $EUID -ne 0 ]; then
	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
	    exit 1
	fi
	
	if [ -z $device ]; then
	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
	    exit 1
	fi

	if ! ip a | grep "$device" >/dev/null 2>&1; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
		exit 1
	fi
	
	change && echo -e "\n${ORANGE}[${BLUE}*${ORANGE}]${GREEN} $device's MAC was changed${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not change MAC Addr of: ${ORANGE}'$device'${NC}"
	echo -e "${ORANGE}"
	macchanger -s $device && echo -e "\n${NC}"
	exit 1

	shift
	break


	;;

	--enable|enable)
	mode=2
	device=$2

	if [ $EUID -ne 0 ]; then
	    echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
	    exit 1
	fi
	
	if [ -z $device ]; then
    		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
    		exit 1
	fi

	if ! ip a | grep "$device" >/dev/null 2>&1; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
       	 	exit 1
	fi
	
	createsv

	enable

	exit 0

	shift
	break

	;;

	--disable|disable)
	mode=3
	device=$3

        if [ $EUID -ne 0 ]; then
    		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
    		exit 1
	fi

	if [ -z $device ]; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
        	exit 1
	fi

	if ! ip a | grep "$device" >/dev/null 2>&1; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
        	exit 1
	fi

	createsv 

	disable

	exit 0

	shift
	break

	;;

	--daemon|daemon)
   	mode=4
	i=$2
	device=$3

	if [ $EUID -ne 0 ]; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
        	exit 1
	fi
	
	if pgrep -a mactd >/dev/null 2>&1; then
		dlist
	fi

	if [ -z $i ]; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing interval(secs)${NC}"
		exit 1
	fi

	if [ -z $device ]; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
        	exit 1
	fi

	if ! ip a | grep "$device" >/dev/null 2>&1; then
		dlist
       	 	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
       		exit 1
	fi

	if ! command -v mactd >> /dev/null 2>&1; then
		echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Missing Daemon${BLUE}(${ORANGE}'mactd',${LB} it should be in your PATH: ${YELLOW}$PATH${BLUE})"
		exit 1
	else
		mactd $i $device && echo -e "\n${ORANGE}[${BLUE}+${ORANGE}]${GREEN} New Daemon Launched !${NC}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknon: ${RED}Could not launch daemon${NC}"
		exit 0
	fi

	shift
	break

	;;
	
	restore|--reset|reset)
	mode=5
	device=$2
        
	if [ $EUID -ne 0 ]; then
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}user is not root${NC}"
        	exit 1
	fi


	if [ -z $device ]; then
        	usage
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${RED}Missing device name${NC}"
        	exit 1
	fi


	if ! ip a | grep "$device" >/dev/null 2>&1; then
        	usage
        	echo -e "\n${RED}[${NC}-${RED}]${NC} Bad usage: ${YELLOW}'$device', ${RED}No such device${NC}"
        	exit 1
	fi

	restore && echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} $device's MAC was restored${ORANGE}" || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}Could not restore MAC of: ${YELLOW}'$device'${ORANGE}"
	macchanger -s $device && echo -e "\n${NC}"
	exit 0
	
	shift
	break

	;;
	
	--show-devices|show)
	mode=6
	
	echo -e "\n${ORANGE}[${BLUE}!${ORANGE}]${GREEN} Available Devices${NC}:" && ip link || echo -e "\n${RED}[${NC}-${RED}]${NC} unknown: ${RED}could not show devices${NC}"

	exit 0
	shift
	break
	
	;;

	--*|-*|*)
	mode=6

	usage
	exit 1

	shift
	break

	;;
esac
done

if [ -z $mode ]; then
	usage
	exit 1
fi
